name: lilynotes
description: "Lily Notes â€” a widget-based note-taking app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2
  uuid: ^4.5.1
  url_launcher: ^6.3.1
  intl: ^0.19.0
  shared_preferences: ^2.3.4
  confetti: ^0.8.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "C:\\Users\\Toms\\Downloads\\liltnotes\\unnamed.jpg"
  adaptive_icon_background: "#009688"
  adaptive_icon_foreground: "C:\\Users\\Toms\\Downloads\\liltnotes\\unnamed.jpg"

flutter_native_splash:
  color: "#009688"
  image: "C:\\Users\\Toms\\Downloads\\liltnotes\\unnamed.jpg"
  android: true
  ios: true

flutter:
  uses-material-design: true
